### ISSUE TITLE
Não funciona no Magento 2.2.5 #122

### ISSUE THREAD

**Issue by ianitsky** [ianitsky/pagseguro-magento2#1]
Ok @blopa , entendi.

Isso acontece pois fiz uma modificação nesse arquivo:

vendor/pagseguro/magento2/Model/PaymentMethod.php:63

Ele estava recebendo uma session, tive que fazê-lo receber uma order, pois estou utilizando o módulo via api e dessa forma não existe sessão.

Pode me ajudar nessa?

Creio que aqui a questão é modificar essa linha:
vendor/pagseguro/magento2/Controller/Payment/Checkout.php:58
para que envie o pedido que está na sessão, e não a sessão em si.
Mas como não estou usando o frontend do magento, não tenho como testar.
Consegue alterar os arquivos e verificar se funciona?

**Comment by blopa** [comment]
Opa. Beleza. Mandei um PR com todas as mudanças que eu fiz. Não ta bonito não, mas ta funcionando. hahaha

PR #2

**Comment by iget-esoares** [comment]
@ianitsky Este seu fork está funcionando no 2.2.X normalmente? Precisa de ajuda para resolver alguma issue?

**Comment by ianitsky** [comment]
Olá @iget-esoares. Até onde testei sim, está funcionando.

O @blopa  fez um PR, precisa ser testado com o módulo do paypal, pois ele disse que junto não está funcionando, para que possa integrar com esse módulo aqui.

Cara, qualquer ajuda será bem vinda. Se puder instalar e fazer os PRs do que achar que está ruim, agradeceria muito.

**Comment by Lgusuco** [comment]
@ianitsky Para instalar seu módulo é apenas dar um composer require pagseguro/magento2 ?

**Comment by ianitsky** [comment]
@Lgusuco, coloque no composer.json

"require": {
    "pagseguro/magento2": "^1",
},

"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/ianitsky/pagseguro-magento2.git"
    },
],

**Comment by Lgusuco** [comment]
@ianitsky Qual token deve ser usado aqui ?

Your GitHub credentials are required to fetch private repository metadata (https://github.com/ianitsky/pagseguro-magento2.git)
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+ip-45-33-12-18+2019-02-12+1252
to retrieve a token. It will be stored in "/home/eldergames/.config/composer/auth.json" for future use by Composer.

**Comment by Lgusuco** [comment]
@ianitsky Funciona na versão 2.2.6 ?

**Comment by Lgusuco** [comment]
@ianitsky Você já teve esse erro no checkout ?

Internal Error. Details are available in Magento log file. Report ID: webapi-5c64ab5f83426

Segue o erro que acontece
https://imgur.com/a/Iw3Ixp2

**Comment by ianitsky** [comment]
@Lgusuco  Cola aqui o conteúdo do arquivo que está na pasta var/report/api/webapi-5c64ab5f83426 ou algo similar

**Comment by Lgusuco** [comment]
@ianitsky Problema é esse não loga nada lá

O estranho quer logo que instalei o modulo deu esse erro.

1 exception(s):
Exception #0 (Exception): Notice: iconv_strlen(): Detected an illegal character in input string in /srv/app403.2d210c12.configr.cloud/www/vendor/magento/zendframework1/library/Zend/Validate/StringLength.php on line 250

Exception #0 (Exception): Notice: iconv_strlen(): Detected an illegal character in input string in /srv/app403.2d210c12.configr.cloud/www/vendor/magento/zendframework1/library/Zend/Validate/StringLength.php on line 250
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(8, 'iconv_strlen():...', '/srv/app403.2d2...', 250, Array)
#1 /srv/app403.2d210c12.configr.cloud/www/vendor/magento/zendframework1/library/Zend/Validate/StringLength.php(250): iconv_strlen('Configura\xC3\xA7\xC3\xB5es')
#2 /srv/app403.2d210c12.configr.cloud/www/app/code/Magento/Backend/Model/Menu/Item/Validator.php(93): Zend_Validate_StringLength->isValid('Configura\xC3\xA7\xC3\xB5es')
#3 /srv/app403.2d210c12.configr.cloud/www/app/code/Magento/Backend/Model/Menu/Item.php(180): Magento\Backend\Model\Menu\Item\Validator->validate(Array)
#4 /srv/app403.2d210c12.configr.cloud/www/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Backend\Model\Menu\Item-
