### ISSUE TITLE
Problemas com a versão 2.2.6

### ISSUE THREAD

**Issue by ludioao** [ianitsky/pagseguro-magento2#3]
@ianitsky agradeço o empenho em dar continuidade no projeto abandonado pelo próprio pagseguro, todavia não estou conseguindo fazer com que funcione na minha instalação.

atualmente estou com a seguinte stack:
- magento: v2.2.6
- php: v7.1.26
- mysql: v5.7

o erro recebido é
```error
Got error 'PHP message: PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\\Framework\\ObjectManager\\ContextInterface in /public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50\nStack trace:\n#0 /public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Framewo...')\n#1 /public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Framewo...')\n#2 /public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, 'Magento\\\\Framewo...', NULL, 'context', 'UOL\\\\PagSeguro\\\\M...')\n#3 /public_html/vendor/mag...\n', 
```

**Comment by ianitsky** [comment]
@ludioao , pode fazer update da sua versão? Se ainda assim der problema, me avise.
